[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "temperature"
version = "0.1.0"
description = "Python package template"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "BSD-2-Clause" }
authors = [
    { name = "IHME Math Sciences", email = "ihme.math.sciences@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
]
dependencies = [
    "numpy", "scipy", "pandas", "matplotlib", "xspline==0.0.7", "pplkit", "fire", "tqdm"
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["sphinx", "sphinx-autodoc-typehints", "furo"]

[project.urls]
github = "https://github.com/ihmeuw-msca/temperature"